# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXjDXEgd4R8r2xKCI0XVoXZWuzUnPN_N
"""

import pandas as pd
mashina=pd.DataFrame({
    "Nomi":['Malibu','cobalt','matiz','onix','bmw'],
    "Rusimi":['premier','2-pazitsya','best','premier','x7'],
    "Rangi":['qora','oq','oq','kulrang','qora'],
    "Narxi":['fit flion','200000$','12000$','52000$','qol yetmas'],
})
print(mashina)

mashina.to_excel("mashina.xlsx")